### Get all departments
GET http://localhost:8080/departments
Accept: application/json

### Get single department
GET http://localhost:8080/departments/1
Accept: application/json

### Create new department
POST http://localhost:8080/departments
Content-Type: application/json

{
    "name": "IT Abteilung",
    "color": "#FF5733"
}

### Update department
PUT http://localhost:8080/departments/1
Content-Type: application/json

{
    "name": "IT Support",
    "color": "#33FF57"
}

### Delete department
DELETE http://localhost:8080/departments/1
Accept: application/json
