### Get all shift types
GET http://localhost:8080/api/v1/shifttypes
Accept: application/json

### Get single shift type
GET http://localhost:8080/api/v1/shifttypes/1
Accept: application/json

### Create new shift type
POST http://localhost:8080/api/v1/shifttypes
Content-Type: application/json

{
    "name": "Frühschicht",
    "description": "Frühe Schicht von 6-14 Uhr",
    "duration": "8h",
    "color": "#FF5733"
}

### Update shift type
PUT http://localhost:8080/api/v1/shifttypes/1
Content-Type: application/json

{
    "name": "Spätschicht",
    "description": "Späte Schicht von 14-22 Uhr",
    "duration": "8h",
    "color": "#33FF57"
}

### Delete shift type
DELETE http://localhost:8080/api/v1/shifttypes/1
Accept: application/json
