### Get all users
GET http://localhost:8080/api/v1/users
Accept: application/json

### Get single user
GET http://localhost:8080/api/v1/users/1
Accept: application/json

### Create new user
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "first_name": "Max",
    "last_name": "Mustermann",
    "email": "max.mustermann@firma.de",
    "password": "geheim123",
    "color": "#FF5733",
    "department_id": 1,
    "is_admin": false
}

### Update user
PUT http://localhost:8080/api/v1/users/1
Content-Type: application/json

{
    "first_name": "Maximilian",
    "last_name": "Mustermann",
    "email": "maximilian.mustermann@firma.de",
    "password": "geheim123",
    "color": "#33FF57",
    "department_id": 1,
    "is_admin": true
}

### Delete user
DELETE http://localhost:8080/api/v1/users/1
Accept: application/json
