global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus selbst überwachen
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Schichtplaner Anwendung überwachen
  - job_name: 'schichtplaner'
    static_configs:
      - targets: ['schichtplaner:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s 